apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trivial-go-web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - image: docker.io/kostiscodefresh/simple-web-app:3d9b390
        name: webserver-simple
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: super-secret
